edit:
	g++ match.cpp `pkg-config --cflags --libs opencv` -I../ -o match -O3
	g++ extract.cpp `pkg-config --cflags --libs opencv` -I../ -o extract -O3
	g++ tracking.cpp `pkg-config --cflags --libs opencv` -I../ -o tracking -O3
